" Init Pathogen
filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
filetype plugin indent on

"
" General config
" 

set t_Co=256

set nocompatible
set modelines=0

set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
" set visualbell
" set cursorline
" set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set relativenumber
set undofile
set autoread

let mapleader = ","

nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
" set gdefault
set incsearch
set showmatch
set hlsearch
nnoremap <leader><space> :noh<CR>
" nnoremap <tab> %
" vnoremap <tab> %

"set wrap
"set textwidth=79
"set formatoptions=qrn1
"set colorcolumn=+1

"set list
"set listchars=tab:▸\ ,eol:¬

inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

" nnoremap j gj
" nnoremap k gk
nnoremap ; :

" au FocusLost * :wa

nnoremap <leader>ev <C-w>s<C-w>j<C-w>L:e $MYVIMRC<CR>
nnoremap <leader>es <C-w>s<C-w>j<C-w>L:e ~/.vim/snippets<CR>
autocmd! bufwritepost $MYVIMRC source %
nnoremap <leader>b <Esc>:make<CR>
nnoremap <leader>cn <Esc>:cn<CR>
nnoremap <leader>cp <Esc>:cp<CR>

set backupdir=~/.vim-backups
set undodir=~/.vim-undo
set exrc

set t_ts=]0;
set t_fs=
set title

colorscheme molokai
syntax on

set tabstop=2
set sts=2
set shiftwidth=2
set expandtab

autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif

"
" Plugin config
"

" Command-t config
noremap <leader>o <Esc>:CommandT<CR>
noremap <leader>O <Esc>:CommandTFlush<CR>
noremap <leader>m <Esc>:CommandTBuffer<CR>

" Tagbar config
let g:tagbar_usearrows = 1
nnoremap <leader>l :TagbarToggle<CR>

" Pyflakes config

" Fugitive config
nnoremap <leader>gs <Esc>:Gstatus<CR>
nnoremap <leader>gc <Esc>:Gcommit<CR>
nnoremap <leader>gp <Esc>:Git push<CR>

" NERDtree config
nnoremap <leader>t <Esc>:NERDTreeToggle<CR>

" NERDcommenter config

" Ack config
nnoremap <leader>a :Ack

" Fswitch config
nnoremap <silent> <leader>ff :FSHere<CR>
nnoremap <silent> <leader>fd :FSLeft<CR>
nnoremap <silent> <leader>fg :FSRight<CR>

" Snipmate config
let g:snippets_dir = "~/.vim/snippets/"


"
" Final commands
"

set secure
